package entity;
// Generated 05.06.2012 13:55:11 by Hibernate Tools 3.2.1.GA



/**
 * Answer generated by hbm2java
 */
public class Answer  implements java.io.Serializable {


     private Integer id;
     private String answer;

    public Answer() {
    }

    public Answer(String answer) {
       this.answer = answer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


