package entity;
// Generated 05.06.2012 13:55:11 by Hibernate Tools 3.2.1.GA



/**
 * AnswerQuestion generated by hbm2java
 */
public class AnswerQuestion  implements java.io.Serializable {


     private Integer id;
     private int answerId;
     private int questionId;

    public AnswerQuestion() {
    }

    public AnswerQuestion(int answerId, int questionId) {
       this.answerId = answerId;
       this.questionId = questionId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getAnswerId() {
        return this.answerId;
    }
    
    public void setAnswerId(int answerId) {
        this.answerId = answerId;
    }
    public int getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(int questionId) {
        this.questionId = questionId;
    }




}


