package entity;
// Generated 05.06.2012 13:55:11 by Hibernate Tools 3.2.1.GA



/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private Integer id;
     private String question;
     private int type;
     private Integer correctId;

    public Question() {
    }

	
    public Question(String question, int type) {
        this.question = question;
        this.type = type;
    }
    public Question(String question, int type, Integer correctId) {
       this.question = question;
       this.type = type;
       this.correctId = correctId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public Integer getCorrectId() {
        return this.correctId;
    }
    
    public void setCorrectId(Integer correctId) {
        this.correctId = correctId;
    }




}


