package entity;
// Generated 05.06.2012 13:55:11 by Hibernate Tools 3.2.1.GA



/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private Integer id;
     private String type;

    public Type() {
    }

    public Type(String type) {
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


