package entity;
// Generated 05.06.2012 13:55:11 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String passwordPlain;
     private String salt;
     private Date createdAt;

    public User() {
    }

    public User(String username, String password, String passwordPlain, String salt, Date createdAt) {
       this.username = username;
       this.password = password;
       this.passwordPlain = passwordPlain;
       this.salt = salt;
       this.createdAt = createdAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPasswordPlain() {
        return this.passwordPlain;
    }
    
    public void setPasswordPlain(String passwordPlain) {
        this.passwordPlain = passwordPlain;
    }
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


